export type SupportLevel = 'full' | 'partial';

export interface ScooterModel {
  id: string;
  brand: 'ninebot' | 'xiaomi';
  name: string;
  displayName: string;
  image: any;
  supportLevel: SupportLevel;
  supportNote?: string;
  bleNames: string[]; // BLE advertisement names to match
  hardwareMaxKmh: number; // realistic hardware max
  specs: {
    motor: string;
    battery: string;
    range: string;
    weight: string;
  };
  capabilities: {
    speedUnlock: boolean;
    firmwareFlash: boolean;
    regionChange: boolean;
    policeMode: boolean;
    dashboard: boolean;
  };
}

export const SCOOTER_DATABASE: ScooterModel[] = [
  // ─── NINEBOT FULL SUPPORT ───────────────────────────────────
  {
    id: 'ninebot_zt3_pro',
    brand: 'ninebot',
    name: 'ZT3 Pro',
    displayName: 'Ninebot ZT3 Pro',
    image: require('../../assets/scooters/ZT3_Pro.jpg'),
    supportLevel: 'full',
    bleNames: ['ZT3-', 'Ninebot ZT3'],
    hardwareMaxKmh: 45,
    specs: { motor: '450W', battery: '15.3Ah', range: '70km', weight: '23kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_gt3',
    brand: 'ninebot',
    name: 'GT3',
    displayName: 'Ninebot GT3',
    image: require('../../assets/scooters/GT3.jpg'),
    supportLevel: 'full',
    bleNames: ['GT3-', 'Ninebot GT3'],
    hardwareMaxKmh: 45,
    specs: { motor: '450W', battery: '15.3Ah', range: '70km', weight: '23kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_g3',
    brand: 'ninebot',
    name: 'G3',
    displayName: 'Ninebot G3',
    image: require('../../assets/scooters/G3.jpg'),
    supportLevel: 'full',
    bleNames: ['G3-', 'Ninebot G3'],
    hardwareMaxKmh: 40,
    specs: { motor: '350W', battery: '15.3Ah', range: '70km', weight: '22kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_g2',
    brand: 'ninebot',
    name: 'Max G2',
    displayName: 'Ninebot Max G2',
    image: require('../../assets/scooters/G2.jpg'),
    supportLevel: 'full',
    supportNote: 'ST-Link Vorbereitung empfohlen',
    bleNames: ['G2-', 'Ninebot G2', 'GKA'],
    hardwareMaxKmh: 40,
    specs: { motor: '450W', battery: '25.2Ah', range: '70km', weight: '23.8kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_g30',
    brand: 'ninebot',
    name: 'Max G30',
    displayName: 'Ninebot Max G30',
    image: require('../../assets/scooters/G30.jpg'),
    supportLevel: 'full',
    bleNames: ['G30-', 'Ninebot G30', 'GKA'],
    hardwareMaxKmh: 38,
    specs: { motor: '350W', battery: '15.3Ah', range: '65km', weight: '18.7kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_g30d',
    brand: 'ninebot',
    name: 'Max G30D',
    displayName: 'Ninebot Max G30D',
    image: require('../../assets/scooters/G30D.jpg'),
    supportLevel: 'full',
    bleNames: ['G30D-', 'Ninebot G30D'],
    hardwareMaxKmh: 38,
    specs: { motor: '350W', battery: '15.3Ah', range: '65km', weight: '18.7kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_g30l',
    brand: 'ninebot',
    name: 'Max G30L',
    displayName: 'Ninebot Max G30L',
    image: require('../../assets/scooters/G30L.jpg'),
    supportLevel: 'full',
    bleNames: ['G30L-'],
    hardwareMaxKmh: 38,
    specs: { motor: '350W', battery: '10.2Ah', range: '40km', weight: '17.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f3',
    brand: 'ninebot',
    name: 'F3',
    displayName: 'Ninebot F3',
    image: require('../../assets/scooters/F3.jpg'),
    supportLevel: 'full',
    bleNames: ['F3-', 'Ninebot F3'],
    hardwareMaxKmh: 38,
    specs: { motor: '350W', battery: '15Ah', range: '55km', weight: '20.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f2_pro',
    brand: 'ninebot',
    name: 'F2 Pro',
    displayName: 'Ninebot F2 Pro',
    image: require('../../assets/scooters/F2_Pro.jpg'),
    supportLevel: 'full',
    supportNote: 'ST-Link Vorbereitung empfohlen',
    bleNames: ['F2Pro-', 'F2P-'],
    hardwareMaxKmh: 38,
    specs: { motor: '350W', battery: '15.3Ah', range: '55km', weight: '20.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f2_plus',
    brand: 'ninebot',
    name: 'F2 Plus',
    displayName: 'Ninebot F2 Plus',
    image: require('../../assets/scooters/F2_Plus.jpg'),
    supportLevel: 'full',
    supportNote: 'ST-Link Vorbereitung empfohlen',
    bleNames: ['F2Plus-', 'F2P+'],
    hardwareMaxKmh: 36,
    specs: { motor: '300W', battery: '12.8Ah', range: '45km', weight: '19.2kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f2',
    brand: 'ninebot',
    name: 'F2',
    displayName: 'Ninebot F2',
    image: require('../../assets/scooters/F2.jpg'),
    supportLevel: 'full',
    supportNote: 'ST-Link Vorbereitung empfohlen',
    bleNames: ['F2-'],
    hardwareMaxKmh: 35,
    specs: { motor: '300W', battery: '10.2Ah', range: '38km', weight: '18.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f40',
    brand: 'ninebot',
    name: 'F40',
    displayName: 'Ninebot F40',
    image: require('../../assets/scooters/F40.jpg'),
    supportLevel: 'full',
    bleNames: ['F40-'],
    hardwareMaxKmh: 35,
    specs: { motor: '350W', battery: '14.4Ah', range: '40km', weight: '16.8kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f30',
    brand: 'ninebot',
    name: 'F30',
    displayName: 'Ninebot F30',
    image: require('../../assets/scooters/F30.jpg'),
    supportLevel: 'full',
    bleNames: ['F30-'],
    hardwareMaxKmh: 30,
    specs: { motor: '300W', battery: '10.2Ah', range: '30km', weight: '15.1kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f25',
    brand: 'ninebot',
    name: 'F25',
    displayName: 'Ninebot F25',
    image: require('../../assets/scooters/F25.jpg'),
    supportLevel: 'full',
    bleNames: ['F25-'],
    hardwareMaxKmh: 28,
    specs: { motor: '250W', battery: '7.65Ah', range: '25km', weight: '13.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_f20',
    brand: 'ninebot',
    name: 'F20',
    displayName: 'Ninebot F20',
    image: require('../../assets/scooters/F20.jpg'),
    supportLevel: 'full',
    bleNames: ['F20-'],
    hardwareMaxKmh: 25,
    specs: { motor: '250W', battery: '5.1Ah', range: '20km', weight: '12kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_es4',
    brand: 'ninebot',
    name: 'ES4',
    displayName: 'Ninebot ES4',
    image: require('../../assets/scooters/ES4.jpg'),
    supportLevel: 'full',
    bleNames: ['ES4-', 'Ninebot ES4'],
    hardwareMaxKmh: 30,
    specs: { motor: '300W', battery: '15.3Ah', range: '45km', weight: '14.2kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_es3',
    brand: 'ninebot',
    name: 'ES3',
    displayName: 'Ninebot ES3',
    image: require('../../assets/scooters/ES3.jpg'),
    supportLevel: 'full',
    bleNames: ['ES3-', 'Ninebot ES3'],
    hardwareMaxKmh: 28,
    specs: { motor: '250W', battery: '11.6Ah', range: '30km', weight: '13.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_es2',
    brand: 'ninebot',
    name: 'ES2',
    displayName: 'Ninebot ES2',
    image: require('../../assets/scooters/ES2.jpg'),
    supportLevel: 'full',
    bleNames: ['ES2-', 'Ninebot ES2'],
    hardwareMaxKmh: 28,
    specs: { motor: '250W', battery: '7.65Ah', range: '25km', weight: '12.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_es1',
    brand: 'ninebot',
    name: 'ES1',
    displayName: 'Ninebot ES1',
    image: require('../../assets/scooters/ES1.jpg'),
    supportLevel: 'full',
    bleNames: ['ES1-', 'Ninebot ES1'],
    hardwareMaxKmh: 25,
    specs: { motor: '150W', battery: '5.1Ah', range: '20km', weight: '11.3kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_e45',
    brand: 'ninebot',
    name: 'E45',
    displayName: 'Ninebot E45',
    image: require('../../assets/scooters/E45.jpg'),
    supportLevel: 'full',
    bleNames: ['E45-'],
    hardwareMaxKmh: 30,
    specs: { motor: '300W', battery: '12.8Ah', range: '45km', weight: '16.8kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_e25',
    brand: 'ninebot',
    name: 'E25',
    displayName: 'Ninebot E25',
    image: require('../../assets/scooters/E25.jpg'),
    supportLevel: 'full',
    bleNames: ['E25-'],
    hardwareMaxKmh: 28,
    specs: { motor: '250W', battery: '7.65Ah', range: '25km', weight: '14.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_e22',
    brand: 'ninebot',
    name: 'E22',
    displayName: 'Ninebot E22',
    image: require('../../assets/scooters/E22.jpg'),
    supportLevel: 'full',
    bleNames: ['E22-'],
    hardwareMaxKmh: 25,
    specs: { motor: '200W', battery: '5.2Ah', range: '22km', weight: '13.2kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'ninebot_air_t15',
    brand: 'ninebot',
    name: 'Air T15',
    displayName: 'Ninebot Air T15',
    image: require('../../assets/scooters/Air_T15.jpg'),
    supportLevel: 'full',
    bleNames: ['T15-', 'Air T15'],
    hardwareMaxKmh: 25,
    specs: { motor: '300W', battery: '7.0Ah', range: '15km', weight: '10kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },

  // ─── XIAOMI FULL SUPPORT ────────────────────────────────────
  {
    id: 'xiaomi_m365_pro',
    brand: 'xiaomi',
    name: 'M365 Pro',
    displayName: 'Xiaomi M365 Pro',
    image: require('../../assets/scooters/M365_Pro.jpg'),
    supportLevel: 'full',
    bleNames: ['MiScooterPro', 'MiScooter Pro', 'Mi Electric Scooter Pro'],
    hardwareMaxKmh: 30,
    specs: { motor: '300W', battery: '12.8Ah', range: '45km', weight: '14.2kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'xiaomi_m365',
    brand: 'xiaomi',
    name: 'M365',
    displayName: 'Xiaomi M365',
    image: require('../../assets/scooters/M365.jpg'),
    supportLevel: 'full',
    bleNames: ['MiScooter', 'Mi Electric Scooter'],
    hardwareMaxKmh: 28,
    specs: { motor: '250W', battery: '7.65Ah', range: '30km', weight: '12.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'xiaomi_pro2',
    brand: 'xiaomi',
    name: 'Mi Electric Scooter Pro 2',
    displayName: 'Xiaomi Pro 2',
    image: require('../../assets/scooters/Mi_Pro2.jpg'),
    supportLevel: 'full',
    bleNames: ['MiScooterPro2', 'Mi Scooter Pro2'],
    hardwareMaxKmh: 30,
    specs: { motor: '300W', battery: '12.8Ah', range: '45km', weight: '14.2kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'xiaomi_1s',
    brand: 'xiaomi',
    name: 'Mi Electric Scooter 1S',
    displayName: 'Xiaomi Mi 1S',
    image: require('../../assets/scooters/Mi_1S.jpg'),
    supportLevel: 'full',
    bleNames: ['MiScooter1S', 'Mi Scooter 1S', 'MiElectricScooter1S'],
    hardwareMaxKmh: 28,
    specs: { motor: '250W', battery: '7.65Ah', range: '30km', weight: '12.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'xiaomi_lite',
    brand: 'xiaomi',
    name: 'Mi Electric Scooter Lite',
    displayName: 'Xiaomi Mi Lite',
    image: require('../../assets/scooters/Mi_Lite.jpg'),
    supportLevel: 'full',
    bleNames: ['MiScooterLite', 'Mi Scooter Lite', 'MiElectricScooterLite'],
    hardwareMaxKmh: 25,
    specs: { motor: '250W', battery: '5.2Ah', range: '20km', weight: '10.5kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },
  {
    id: 'xiaomi_mi3',
    brand: 'xiaomi',
    name: 'Mi Electric Scooter 3',
    displayName: 'Xiaomi Mi 3',
    image: require('../../assets/scooters/Mi_3.jpg'),
    supportLevel: 'full',
    supportNote: 'Experimentelle Unterstützung',
    bleNames: ['MiScooter3', 'Mi Electric Scooter 3'],
    hardwareMaxKmh: 25,
    specs: { motor: '300W', battery: '7.65Ah', range: '30km', weight: '13.2kg' },
    capabilities: { speedUnlock: true, firmwareFlash: true, regionChange: true, policeMode: true, dashboard: true },
  },

  // ─── PARTIAL SUPPORT ────────────────────────────────────────
  {
    id: 'ninebot_d38',
    brand: 'ninebot',
    name: 'D38',
    displayName: 'Ninebot D38',
    image: null, // placeholder
    supportLevel: 'partial',
    supportNote: 'Nur Region-Unlock (bis 30 km/h)',
    bleNames: ['D38-', 'Ninebot D38'],
    hardwareMaxKmh: 30,
    specs: { motor: '350W', battery: '10.8Ah', range: '38km', weight: '16kg' },
    capabilities: { speedUnlock: false, firmwareFlash: false, regionChange: true, policeMode: false, dashboard: true },
  },
  {
    id: 'ninebot_d28',
    brand: 'ninebot',
    name: 'D28',
    displayName: 'Ninebot D28',
    image: null,
    supportLevel: 'partial',
    supportNote: 'Nur Region-Unlock (bis 30 km/h)',
    bleNames: ['D28-'],
    hardwareMaxKmh: 30,
    specs: { motor: '300W', battery: '7.5Ah', range: '28km', weight: '15kg' },
    capabilities: { speedUnlock: false, firmwareFlash: false, regionChange: true, policeMode: false, dashboard: true },
  },
  {
    id: 'ninebot_d18',
    brand: 'ninebot',
    name: 'D18',
    displayName: 'Ninebot D18',
    image: null,
    supportLevel: 'partial',
    supportNote: 'Nur Region-Unlock (bis 30 km/h)',
    bleNames: ['D18-'],
    hardwareMaxKmh: 30,
    specs: { motor: '250W', battery: '5.1Ah', range: '18km', weight: '13kg' },
    capabilities: { speedUnlock: false, firmwareFlash: false, regionChange: true, policeMode: false, dashboard: true },
  },
  {
    id: 'xiaomi_4_pro',
    brand: 'xiaomi',
    name: 'Electric Scooter 4 Pro',
    displayName: 'Xiaomi 4 Pro',
    image: null,
    supportLevel: 'partial',
    supportNote: 'Nur Serien-Nr Wechsel (bis 25 km/h)',
    bleNames: ['Mi4Pro-', 'Xiaomi4Pro'],
    hardwareMaxKmh: 25,
    specs: { motor: '350W', battery: '10.2Ah', range: '40km', weight: '18.5kg' },
    capabilities: { speedUnlock: false, firmwareFlash: false, regionChange: true, policeMode: false, dashboard: true },
  },
  {
    id: 'xiaomi_4',
    brand: 'xiaomi',
    name: 'Electric Scooter 4',
    displayName: 'Xiaomi 4',
    image: null,
    supportLevel: 'partial',
    supportNote: 'Nur Serien-Nr Wechsel (bis 25 km/h)',
    bleNames: ['Mi4-', 'Xiaomi4'],
    hardwareMaxKmh: 25,
    specs: { motor: '300W', battery: '7.65Ah', range: '35km', weight: '17kg' },
    capabilities: { speedUnlock: false, firmwareFlash: false, regionChange: true, policeMode: false, dashboard: true },
  },
  {
    id: 'xiaomi_4_lite',
    brand: 'xiaomi',
    name: 'Electric Scooter 4 Lite',
    displayName: 'Xiaomi 4 Lite',
    image: null,
    supportLevel: 'partial',
    supportNote: 'Nur Serien-Nr Wechsel (bis 25 km/h)',
    bleNames: ['Mi4Lite-'],
    hardwareMaxKmh: 25,
    specs: { motor: '250W', battery: '5.2Ah', range: '20km', weight: '14kg' },
    capabilities: { speedUnlock: false, firmwareFlash: false, regionChange: true, policeMode: false, dashboard: true },
  },
  {
    id: 'xiaomi_4_ultra',
    brand: 'xiaomi',
    name: 'Electric Scooter 4 Ultra',
    displayName: 'Xiaomi 4 Ultra',
    image: null,
    supportLevel: 'partial',
    supportNote: 'Nur Serien-Nr Wechsel (bis 25 km/h)',
    bleNames: ['Mi4Ultra-'],
    hardwareMaxKmh: 25,
    specs: { motor: '400W', battery: '12.8Ah', range: '45km', weight: '19kg' },
    capabilities: { speedUnlock: false, firmwareFlash: false, regionChange: true, policeMode: false, dashboard: true },
  },
];

export const getScooterById = (id: string) =>
  SCOOTER_DATABASE.find(s => s.id === id);

export const getScooterByBleName = (bleName: string) =>
  SCOOTER_DATABASE.find(s =>
    s.bleNames.some(n => bleName.toLowerCase().includes(n.toLowerCase()))
  );

export const FULL_SUPPORT = SCOOTER_DATABASE.filter(s => s.supportLevel === 'full');
export const PARTIAL_SUPPORT = SCOOTER_DATABASE.filter(s => s.supportLevel === 'partial');
